language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

sudo: required

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

before_install:
  - make install.tools
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get -t -d ./...

install: true

script:
  - make .gitvalidation
  - make lint
  - make check-license
  - make test
  - make tool
